version: "3.9"

services:
  flask:
    build: flask
    ports:
      - "5000:5000"
    restart: always

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    expose:
      - "80"
    depends_on:
      - flask
    restart: always
